### ISSUE TITLE
Looming regression with 8.10

### ISSUE THREAD

**Issue by AndreasPK** [haskell/base64-bytestring#25]
Encoding takes a serious performance hit with the release candidate of 8.10. See https://gitlab.haskell.org/ghc/ghc/issues/17653

While the root cause seems to be a regression within GHC, it's easily fixed by adding a few bangs to encodeWith. (See also the above ticket). Given that a fix might not make it into 8.10 working around it seems reasonable.

**Comment by hvr** [comment]
I'm a bit worried that there might be quite a few other packages out there which are performance critical and might be affected by this GHC 8.10 regression as well; as such I'd be really disappointed if this isn't considered a release-blocker on GHC's end. I'd hope the recent trend that started around GHC 8.4 of rushing out new major GHC versions at the cost of releasing with more criticial bugs than before as well as burdening the ecosystem and infrastructure with more major releases for no benefit as far as I'm concerned would be reconsidered... 

`<rant>`I for one are rather reluctant to start going through all my packages' benchmarks and add workarounds (to be clear I strongly disagree terming this a "fix" when it is in fact a workaround) for what appears to be a regression on GHC's side rather than the affected packages' fault. And quite frankly it feels like busy-work having to re-check & re-tune most hand-tuned code when every new GHC major version's optimizer changes in ways that invalidates previously well working implementations...`</rant>`

**Comment by cartazio** [comment]
this is a pretty bad ghc regression. Performance characteristics are an important  part of a major compiler release... how many other similar libs are hit?

**Comment by sgraf812** [comment]
As I said in https://gitlab.haskell.org/ghc/ghc/issues/17653#note_245891, I actually think that reverting the responsible change to demand analysis until we have a proper story for side-effect free state thread prim-ops.

But nonetheless, demand analysis should actually not inferred `encodeWith` to be strict in the `EncodeTable`s fields (why aren't they strict in the first place?). What if its fields contained exceptions? Evaluating them eagerly would discard all the (write) side-effects that would have happened until the fields where finally forced. Hence demand analysis is correct. Putting the bangs there is mandatory to semantics.

**Comment by 23Skidoo** [comment]
Fixed by #27.
